### ISSUE TITLE
Layout Issue in Major Browsers

### ISSUE THREAD

**Issue by heyalexej** [ytspar/ristrettogram#26]
![selection_001](https://cloud.githubusercontent.com/assets/2575014/10906263/a8e9b3a8-8252-11e5-8972-40ca67d9cab5.png)

Other major browsers: http://www.crossbrowsertool.com/s/978271

```css
media="screen"
.touch, #main-content {
    overflow-y: scroll; /* <- offender */ 
```

**Comment by ytspar** [comment]
Goddamn IE

Yeah, I'll look at that - I recall something about the need for `overflow-y: scroll` to enable smooth scrolling for touch devices. I could limit it specifically to iPhone.

**Comment by heyalexej** [comment]
Happens on a multitude of OSs and browsers though - iOS included.

**Comment by ytspar** [comment]
I don't see the issue on iOS, but regardless, needs a fix.

**Comment by ytspar** [comment]
lol almost fixed, except for IE

**Comment by heyalexej** [comment]
[![LGTM](http://lgtm.in/p/2ZYYZ4rWp)](http://lgtm.in/i/2ZYYZ4rWp)
