### ISSUE TITLE
Breaking changes in config.rb

### ISSUE THREAD

**Issue by heyalexej** [ytspar/ristrettogram#6]
[This](https://github.com/ytspar/ristrettogram/blob/7862d43036db6fd50fad29e1e4dcd3d89c63e666/config.rb#L157-L172) breaks middleman when you don't have the config file.

Output from `bundle exec middleman server`:

```sh
== The Middleman is loading
/tmp/ristrettogram/config.rb:158:in `initialize': No such file or directory @ rb_sysopen - aws.yml (Errno::ENOENT)
	from /tmp/ristrettogram/config.rb:158:in `open'
	from /tmp/ristrettogram/config.rb:158:in `initialize'
```

**Comment by ytspar** [comment]
So could either add the `aws.yml` file, or I an make its loading conditioned on being in the `build` group.
